from tkinter import *
root=Tk()
a=Menu(root)
root.config(menu=a)
b=Menu(a)
c=Menu(b)

a.add_cascade(label="file",menu=b)
b.add_cascade(label="New project",menu=c)
c.add_command(label="list project")
b.add_command(label="close project")
b.add_separator()
b.add_command(label="New")
b.add_command(label="Save")
b.add_command(label="Exit",command=quit)

d=Menu(a)
a.add_cascade(label="Edit",menu=d)
d.add_command(label="total window")
d.add_command(label="copy")
d.add_command(label="cut")
d.add_separator()
d.add_command(label="past")
d.add_command(label="undo")
d.add_command(label="delete")

e=Menu(a)
a.add_cascade(label="Navigate",menu=e)
e.add_command(label="back")
e.add_command(label="search")
e.add_separator()
e.add_command(label="class")
e.add_command(label="command")

f=Menu(a)
a.add_cascade(label="code",menu=f)
f.add_command(label="generate")
f.add_command(label="generate2")
f.add_separator()
f.add_command(label="generate3")
f.add_command(label="generate4")

toolbar=Frame(root,bg="pink")
z=Button(toolbar,text="cut")
z.pack(side=LEFT,padx=0,pady=3)
z1=Button(toolbar,text="copy")
z1.pack(side=LEFT,padx=0,pady=3)
toolbar.pack(side=TOP,fill=X)

root.mainloop()